input {
  beats {
    port => 5044
  }
}

filter {
  if "airflow" in [log][file][path] {
    mutate {
      add_field => { "source" => "airflow" }
    }
  }

  if "docker" in [container] {
    mutate {
      add_field => { "source" => "docker" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{source}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
